Test the upgrade process from several approaches to confirm it is indeed upgradeable
zer0-os/ZToken_legacy pull request #26
Opened 2023-10-11 19:50 UTC by JamesEarle

I had skepticism about using the HardHat validation script as our only validation tool against the contract and so I've provided several tests that check the validation, intentionally fail the validation, and also run the upgrade outside of the hardhat plugin

2023-10-12 17:50 UTC, Whytecrowe commented on contracts/ZeroToken.sol
> +// SPDX-License-Identifier: MIT
let's maybe mark this contract, so we know it's not the one being deployed. a comment or something at least, so we know it's the old version of the token

2023-10-12 17:51 UTC, Whytecrowe commented on contracts/ZeroToken.sol
> +
what's the difference between this and LiveZeroToken.sol?

2023-10-13 13:17 UTC, JamesEarle commented on contracts/ZeroToken.sol
> +
messaged you so going to close this

2023-10-13 21:29 UTC, Whytecrowe commented on test/meowToken.test.ts
> +  describe("#transferBulk", () => {
check the burn process here and in another function as well.
now if we send tokens to this contract they should be burned from `totalSupply`

2023-10-13 21:32 UTC, Whytecrowe commented on test/upgrades.test.ts
> +    );
can add `should.be.fulfilled` from Chai to have a proper test case. it will make sure the promise returns properly

2023-10-13 21:34 UTC, Whytecrowe commented on test/upgrades.test.ts
> +    const call = hre.upgrades.validateUpgrade(
this is not a test technically :) you do not await here, so it can be a promise with an error inside and the test will not know.
add `should.be.fulfilled` from the previous comment as in that test.
also `call` var is not used.

2023-10-16 12:58 UTC, JamesEarle commented on test/upgrades.test.ts
> +    const call = hre.upgrades.validateUpgrade(
forgot to come back to this one before committing, but already fixed it and also have now added the change I mentioned above for clarity of the promise

2023-10-16 13:00 UTC, JamesEarle commented on test/upgrades.test.ts
> +    );
I will add this for clarity, but contextually it performs a `throw Error` internally if there is a problem so the test would not be passing unless it is valid.

2023-10-16 13:30 UTC, JamesEarle commented on test/upgrades.test.ts
> +    );
Actually this seems to be causing an error because although it is a promise that is awaited, it is a `Promise<void>` and so is throwing an `{...} is not a thenable` error, meaning I can't use `should` assertions as it is expecting to return a value but that isn't the case

To still make this clearer and more of a "test" I can simply do the below instead. Let me know if you have any other preferred way

```
await expect(...).to.not.be.rejected;
```

2023-10-17 19:25 UTC, Whytecrowe commented on contracts/MeowToken.sol
> +    _mint(_msgSender(), amount);
remove this?

2023-10-17 19:26 UTC, Whytecrowe commented on .circleci/config.yml
> +version: 2.1
thanks for adding this! I don't see it in Circle yet, though. let's add this there properly so we can track tests there and it runs on every push

2023-10-17 19:33 UTC, Whytecrowe commented on test/liveZeroToken.test.ts
> +        // TODO fix this
what is this one for?

2023-10-17 19:41 UTC, Whytecrowe commented on test/upgrades.test.ts
> +  // TODO add tests to run same token tests we already have but for before and after the upgrade
please, address these

2023-10-17 19:42 UTC, Whytecrowe requested changes
please, address comments

2023-10-17 20:28 UTC, JamesEarle commented on contracts/MeowToken.sol
> +    _mint(_msgSender(), amount);
To not break the tests I made a `MeowTokenTest` contract that is identcial to `MeowToken` but the real contract no longer contains this.

2023-10-17 20:29 UTC, JamesEarle commented on test/liveZeroToken.test.ts
> +        // TODO fix this
old comment :)

2023-10-18 19:00 UTC, JamesEarle commented on .circleci/config.yml
> +version: 2.1
I've gotten this working now, it wasn't initially plugged in but as you can see it's passing below

2023-10-18 21:39 UTC, merged